FEC-11456 Playlist support.
kaltura/playkit-ios pull request #435
Opened 2021-09-02 14:00 UTC by chausov

FEC-11456 Playlist support.

2021-11-09 18:11 UTC, chausov commented on Classes/Events/PublicMessageBus.swift
> +public protocol PublicMessageBus {
Maybe we need to rename this class

2021-12-15 12:27 UTC, chausov commented on Classes/Events/PlaylistEvent.swift
> +    public class  PlaylistCurrentPlayingItemChanged: PlaylistEvent {}
@x-NR-x  Do we need a payload, any event data for this event?

2021-12-15 12:33 UTC, chausov commented on Classes/Events/PlaylistEvent.swift
> +    public class PlaylistLoaded: PlaylistEvent {}
@x-NR-x should we have any payload for: PlaylistLoaded, PlaylistStarted, PlaylistEnded, PlaylistCountDownStart, PlaylistCountDownEnd, PlaylistLoopStateChanged, PlaylistAutoContinueStateChanged ?

2021-12-29 16:52 UTC, x-NR-x requested changes

2021-12-29 16:52 UTC, x-NR-x commented on Classes/Events/PlaylistEvent.swift
> +        playListLoaded, playListStarted, playListEnded, playlistCountDownStart, playlistCountDownEnd, playlistLoopStateChanged, playlistLoopStateChanged, playlistAutoContinueStateChanged, playListErr
Let's keep all in the same format: 'playlist'.
```suggestion
        playlistLoaded, playlistStarted, playlistEnded, playlistCountDownStart, playlistCountDownEnd, playlistLoopStateChanged, playlistLoopStateChanged, playlistAutoContinueStateChanged, playlistError, playlistLoadMediaError, playlistCurrentPlayingItemChanged
```

2021-12-29 16:52 UTC, x-NR-x commented on Classes/Events/PlaylistEvent.swift
> +    public class PlaylistLoaded: PlaylistEvent {}
After adding this to the samples with a complete UI, I saw that only PlaylistCountDownStart needs the duration of the countdown. (I will commit the addition)
Because there is only one playlist active at a time, no additional data is needed.

2021-12-29 16:52 UTC, x-NR-x commented on Classes/Events/PlaylistEvent.swift
> +    public class  PlaylistCurrentPlayingItemChanged: PlaylistEvent {}
After adding this to the samples with a complete UI, It will only be nice to have the index but not mandatory.
It is available on the player as the following:
kalturaBasicPlayer.playlistController?.currentMediaIndex

2021-12-29 16:52 UTC, x-NR-x commented on Classes/Player/Media/PKMediaEntry.swift
> +    @objc public init(_ id: String, sources: [PKMediaSource]?, duration: TimeInterval = 0) {
Why was this changed?
Can't create a PKMediaEntry without a source.

2021-12-29 16:52 UTC, x-NR-x commented on Classes/Events/PublicMessageBus.swift
> +public protocol PublicMessageBus {
Can be PKMessageBus. (I will commit the change.)

2021-12-29 17:32 UTC, x-NR-x approved these changes

2021-12-29 17:37 UTC, x-NR-x commented on Classes/Player/Media/PKMediaEntry.swift
> +    @objc public init(_ id: String, sources: [PKMediaSource]?, duration: TimeInterval = 0) {
Saw the change that was needed for it.

2021-12-29 17:40 UTC, merged